apiVersion: apps/v1  # Correct apiVersion for Deployment
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1  # Number of replicas (optional, defaults to 1 if omitted)
  selector:    # Required for Deployment
    matchLabels:
      app: flask-app
  template:    # Pod template
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: ibrahimaamer/flask-app-pipeline:latest
        ports:
        - containerPort: 5000
